version: 1
formatters:
  simple:
    format: '%(asctime)s -%(processName)s-%(process)d- %(name)s -%(thread)d  -%(threadName)s - %(levelname)s -%(lineno)d -%(funcName)s- %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  debug_handler:
                class:  logging.handlers.TimedRotatingFileHandler
                level: DEBUG
                formatter: simple
                filename: /log_info/ft-subclass_debug.log
                encoding: utf-8
  error_handler:
    class:  logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: simple
    filename: /log_info/ft-subclass_error.log
    encoding: utf-8
  info_handler:
    class:  logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: /log_info/ft-subclass_info.log
    encoding: utf-8
    when: D

loggers:
  py_grpc:
    level: DEBUG
    handlers: [console,debug_handler,error_handler,info_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console,debug_handler,error_handler,info_handler]